server:
  port: 7174
  servlet:
    context-path: /api/ms-shipment/v1

spring:
  application:
    name: shipment-service
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:shipmentsdb}?useSSL=true
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}

  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update

  rabbitmq:
    host: ${RABBIT_MQ_HOST_NAME:localhost}
    port: ${RABBIT_MQ_PORT:5672}
    username: ${RABBIT_MQ_USER:guest}
    password: ${RABBIT_MQ_PASSWORD:guest}
    listener:
      direct:
        acknowledge-mode: manual

amqp:
  bindings:
      -
        exchange: payment.events
        routingKey: payment.completed
        queue: payment.completed.shipment-service

      -
        exchange: shipment.events
        routingKey: shipment.completed
        queue: shipment.completed.order-service

      -
        exchange: shipment.events
        routingKey: shipment.failed
        queue: shipment.failed.payment-service

  queues:
    shipment_completed: shipment.completed.order-service
    shipment_failed: shipment.failed.payment-service
    payment_completed: payment.completed.shipment-service

  routingKey:
    shipment_completed_events: shipment.completed
    shipment_failed_events: shipment.failed

  exchange:
    shipment_events: shipment.events