server:
  port: 7172
  servlet:
    context-path: /api/ms-payment/v1

spring:
  application:
    name: payment-service
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:paymentsdb}?useSSL=true
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}

  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update

  rabbitmq:
    host: ${RABBIT_MQ_HOST_NAME:localhost}
    port: ${RABBIT_MQ_PORT:5672}
    username: ${RABBIT_MQ_USER:guest}
    password: ${RABBIT_MQ_PASSWORD:guest}
    listener:
      direct:
        acknowledge-mode: manual

amqp:
  bindings:
    -
      exchange: payment.events
      routingKey: payment.completed
      queue: payment.completed.shipment-service

    -
      exchange: payment.events
      routingKey: payment.failed
      queue: payment.failed.order-service

    -
      exchange: order.events
      routingKey: order.created
      queue: order.created.payment-service

    -
      exchange: shipment.events
      routingKey: shipment.failed
      queue: shipment.failed.payment-service

  queues:
    payment_completed: payment.completed.shipment-service
    payment_failed: payment.failed.order-service
    order_created: order.created.payment-service
    shipment_failed: shipment.failed.payment-service

  routingKey:
    payment_completed_events: payment.completed
    payment_failed_events: payment.failed

  exchange:
    payment_events: payment.events